let bookmarks=[];
document.addEventListener("DOMContentLoaded",async()=>{mountSidebar("bookmarks");bookmarks=await getBookmarks();populateCategories();render();qs("#bookmarkSearch").oninput=render;qs("#categorySelect").onchange=render;qs("#favoritesOnly").onchange=render;qs("#exportBtn").onclick=exportJson;qs("#importBtn").onclick=()=>qs("#fileInput").click();qs("#fileInput").onchange=importJson;qs("#addBtn").onclick=()=>qs("#bookmarkDialog").showModal();qs("#bookmarkForm").onsubmit=saveNew;});
function populateCategories(){const cats=[...new Set([...getCategories(),...bookmarks.map(b=>b.category)])].sort();qs("#categorySelect").innerHTML=`<option value="">All categories</option>`+cats.map(c=>`<option>${escapeHtml(c)}</option>`).join("");}
function render(){const q=qs("#bookmarkSearch").value.toLowerCase(),cat=qs("#categorySelect").value,fav=qs("#favoritesOnly").checked;const list=bookmarks.filter(b=>(!q||[b.title,b.description,b.category,...b.tags].join(" ").toLowerCase().includes(q))&&(!cat||b.category===cat)&&(!fav||b.favorite));qs("#bookmarkList").innerHTML=list.map(b=>`<article class="resource-card"><div class="resource-icon">${b.favorite?"⭐":"🔖"}</div><div class="resource-main"><h3>${escapeHtml(b.title)}</h3><p>${escapeHtml(b.description||b.url)}</p><div>${escapeHtml(b.category)} ${b.tags.map(t=>`<span class="tag">${escapeHtml(t)}</span>`).join(" ")}</div><small>Updated ${formatDate(b.updatedAt)}</small></div><div class="resource-actions"><button data-open="${escapeAttr(b.url)}">Open</button><button data-fav="${b.id}">${b.favorite?"★":"☆"}</button><button data-del="${b.id}" class="danger">Delete</button></div></article>`).join("")||`<div class="empty">No bookmarks match your filters.</div>`;qsa("[data-open]").forEach(x=>x.onclick=()=>chrome.tabs.create({url:x.dataset.open}));qsa("[data-fav]").forEach(x=>x.onclick=()=>toggleFav(x.dataset.fav));qsa("[data-del]").forEach(x=>x.onclick=()=>deleteBookmark(x.dataset.del));}
async function toggleFav(id){bookmarks=bookmarks.map(b=>b.id===id?{...b,favorite:!b.favorite,updatedAt:new Date().toISOString()}:b);await saveBookmarks(bookmarks);render();}
async function deleteBookmark(id){if(!confirm("Delete this bookmark?"))return;bookmarks=bookmarks.filter(b=>b.id!==id);await saveBookmarks(bookmarks);render();toast("Bookmark deleted");}
async function saveNew(e){e.preventDefault();const f=new FormData(e.target);const b=normalizeBookmark({title:f.get("title"),url:f.get("url"),category:f.get("category")||"Uncategorized",tags:String(f.get("tags")||"").split(",").map(x=>x.trim()).filter(Boolean),difficulty:f.get("difficulty"),description:f.get("description"),notes:f.get("notes"),favorite:true});bookmarks.push(b);await saveBookmarks(bookmarks);e.target.reset();qs("#bookmarkDialog").close();populateCategories();render();toast("Bookmark saved","success");}
function download(name,text,type="application/json"){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
async function exportJson(){download(`DevOps-Bookmarks-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify({version:1,exportedAt:new Date().toISOString(),bookmarks},null,2));toast("Bookmarks exported","success");}
async function importJson(e){const file=e.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text());const incoming=(Array.isArray(data)?data:data.bookmarks||[]).map(normalizeBookmark);const map=new Map(bookmarks.map(b=>[b.url,b]));incoming.forEach(b=>{if(!map.has(b.url))map.set(b.url,b);});bookmarks=[...map.values()];await saveBookmarks(bookmarks);populateCategories();render();toast(`Imported ${incoming.length} bookmarks`,"success");}catch(err){toast(`Import failed: ${err.message}`,"error");}e.target.value="";}
function mountSidebar(active){const nav=[["dashboard","⌂","Home"],["search","⌕","Search"],["bookmarks","☆","Bookmarks"],["roadmap","◎","Roadmap"],["toolbox","▦","Toolbox"],["health","◉","Health"],["settings","⚙","Settings"]];qs("#sidebar").innerHTML=`<div class="side-brand"><span>🚀</span><b>DevOps Explorer</b></div><nav>${nav.map(([p,i,l])=>`<a class="${active===p?"active":""}" href="../${p}/${p}.html">${i}<span>${l}</span></a>`).join("")}</nav>`;}