import { APP_VERSION, deriveRawBase, deriveRawIndex } from '../../js/config.js';
import { getConfig, saveConfig, getBookmarks, saveBookmarks, getHistory, addHistory, getNotes, saveNotes, getLearning, saveLearning } from '../../js/storage.js';
import { CATEGORIES, TYPES, DIFFICULTIES, ROADMAP, inferCategory, makeId } from '../../js/data.js';
import { checkEndpoint, fetchRawFile, githubGetFile, githubPutFile, getRepoMetadata } from '../../js/github.js';

const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
let config, bookmarks, notes, learning, resources = [];
let selectedCategories = new Set();
const builtInResources = [
  {title:'Kubernetes Documentation',url:'https://kubernetes.io/docs/',category:'Kubernetes',tags:['kubernetes','docs','containers'],type:'documentation',difficulty:'beginner'},
  {title:'Docker Documentation',url:'https://docs.docker.com/',category:'Containers',tags:['docker','containers'],type:'documentation',difficulty:'beginner'},
  {title:'Jenkins Documentation',url:'https://www.jenkins.io/doc/',category:'CI/CD',tags:['jenkins','pipeline','cicd'],type:'documentation',difficulty:'beginner'},
  {title:'Terraform Documentation',url:'https://developer.hashicorp.com/terraform/docs',category:'Infrastructure as Code',tags:['terraform','iac'],type:'documentation',difficulty:'intermediate'},
  {title:'AWS EKS Documentation',url:'https://docs.aws.amazon.com/eks/',category:'Cloud',tags:['aws','eks','kubernetes'],type:'documentation',difficulty:'intermediate'},
  {title:'GitHub Actions Documentation',url:'https://docs.github.com/actions',category:'CI/CD',tags:['github','actions','cicd'],type:'documentation',difficulty:'beginner'},
  {title:'Prometheus Documentation',url:'https://prometheus.io/docs/',category:'Observability',tags:['prometheus','monitoring'],type:'documentation',difficulty:'intermediate'},
  {title:'Grafana Documentation',url:'https://grafana.com/docs/',category:'Observability',tags:['grafana','monitoring'],type:'documentation',difficulty:'beginner'},
  {title:'Argo CD Documentation',url:'https://argo-cd.readthedocs.io/',category:'GitOps',tags:['argocd','gitops','kubernetes'],type:'documentation',difficulty:'advanced'},
  {title:'Trivy Documentation',url:'https://trivy.dev/',category:'Security',tags:['trivy','security','containers'],type:'documentation',difficulty:'intermediate'},
  {title:'Ansible Documentation',url:'https://docs.ansible.com/',category:'Infrastructure as Code',tags:['ansible','automation'],type:'documentation',difficulty:'intermediate'},
  {title:'Helm Documentation',url:'https://helm.sh/docs/',category:'Kubernetes',tags:['helm','kubernetes','package'],type:'documentation',difficulty:'intermediate'}
];

const toast = msg => { const el=$('#toast'); el.textContent=msg; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),2400); };
const escapeHtml = s => String(s ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const openUrl = url => { if(url) { chrome.tabs.create({url}); addHistory({title:url, url}); } };
const pct = (a,b)=>b?Math.round(a/b*100):0;

async function loadResources(){
  resources = [...builtInResources];
  if(config.rawBaseUrl){
    try {
      const raw = await fetchRawFile('data/resources.json');
      const data = JSON.parse(raw);
      const arr = Array.isArray(data)?data:(Array.isArray(data.resources)?data.resources:[]);
      resources = arr.map(x=>({title:x.title||x.name||'Untitled',url:x.url||x.link||'',category:x.category||inferCategory(x.title||x.name,x.tags||''),tags:Array.isArray(x.tags)?x.tags:String(x.tags||'').split(',').map(t=>t.trim()).filter(Boolean),type:x.type||'github-repository',difficulty:x.difficulty||'intermediate',description:x.description||''})).filter(x=>x.url);
      toast(`Loaded ${resources.length} resources from GitHub.`);
    } catch { /* built-in fallback */ }
  }
}

function renderQuick(){
  $('#quickAccess').innerHTML=CATEGORIES.map(c=>`<button class="tech" data-tool="${escapeHtml(c.name)}">${c.icon}<br><span class="small">${escapeHtml(c.name)}</span></button>`).join('');
  $$('#quickAccess [data-tool]').forEach(b=>b.onclick=()=>{showSection('search'); $('#searchQuery').value=b.dataset.tool; runSearch();});
}

function fillCategories(){
  $('#searchCategory').innerHTML=CATEGORIES.map(c=>`<option value="${escapeHtml(c.name)}">${c.icon} ${escapeHtml(c.name)}</option>`).join('');
  $('#bookmarkCategory').innerHTML='<option value="">All categories</option>'+CATEGORIES.map(c=>`<option>${escapeHtml(c.name)}</option>`).join('');
  $('#categoryChips').innerHTML=CATEGORIES.map(c=>`<button class="chip" data-cat="${escapeHtml(c.name)}">${c.icon} ${escapeHtml(c.name)}</button>`).join('');
  $$('#categoryChips [data-cat]').forEach(btn=>btn.onclick=()=>{const v=btn.dataset.cat;if(selectedCategories.has(v)){selectedCategories.delete(v);btn.classList.remove('selected')}else{selectedCategories.add(v);btn.classList.add('selected')}$('#searchCategory').value=[...selectedCategories];});
}

async function renderStats(){
  const collections=new Set(bookmarks.flatMap(b=>b.collections||[])); const learningDone=ROADMAP.filter(([name,status])=>(learning[name]||status)==='Completed').length;
  $('#statBookmarks').textContent=bookmarks.length;$('#statCollections').textContent=collections.size;$('#statNotes').textContent=Object.keys(notes).length;$('#statProgress').textContent=`${pct(learningDone,ROADMAP.length)}%`;
  $('#homeBookmarks').textContent=bookmarks.length; $('#statProgress').title=`${learningDone}/${ROADMAP.length} completed`;
}

function renderRecent(){
  const h = getHistory().then(list=>{ $('#recentList').innerHTML=list.length?list.slice(0,8).map(x=>`<div class="health-row"><span><strong>${escapeHtml(x.title)}</strong><br><span class="muted small">${escapeHtml(x.url)}</span></span><button class="btn" data-open="${encodeURIComponent(x.url)}">Open</button></div>`).join(''):'<div class="empty">No recently opened resources yet.</div>'; $$('#recentList [data-open]').forEach(b=>b.onclick=()=>openUrl(decodeURIComponent(b.dataset.open))); }); return h;
}

function renderBookmarks(){
  const q=($('#bookmarkSearch').value||'').toLowerCase(); const cat=$('#bookmarkCategory').value;
  const list=bookmarks.filter(b=>(!cat||b.category===cat)&&(!q||JSON.stringify(b).toLowerCase().includes(q)));
  $('#bookmarkBody').innerHTML=list.length?list.map(b=>`<tr><td><strong>${escapeHtml(b.title)}</strong><br><span class="muted small">${escapeHtml(b.url)}</span></td><td>${escapeHtml(b.category||'Other')}</td><td>${(b.tags||[]).map(t=>`<span class="pill">#${escapeHtml(t)}</span> `).join('')}</td><td>${escapeHtml(b.difficulty||'—')}</td><td>${(b.collections||[]).map(c=>`<span class="pill">${escapeHtml(c)}</span> `).join('')}</td><td><div class="toolbar"><button class="btn" data-open="${encodeURIComponent(b.url)}">Open</button><button class="btn" data-edit="${b.id}">Edit</button><button class="btn danger" data-delete="${b.id}">Delete</button></div></td></tr>`).join(''):'<tr><td colspan="6"><div class="empty">No bookmarks match your filters.</div></td></tr>';
  $$('#bookmarkBody [data-open]').forEach(b=>b.onclick=()=>openUrl(decodeURIComponent(b.dataset.open)));
  $$('#bookmarkBody [data-edit]').forEach(b=>b.onclick=()=>openBookmarkModal(bookmarks.find(x=>x.id===b.dataset.edit)));
  $$('#bookmarkBody [data-delete]').forEach(b=>b.onclick=async()=>{bookmarks=bookmarks.filter(x=>x.id!==b.dataset.delete);await saveBookmarks(bookmarks);renderBookmarks();renderStats();toast('Bookmark deleted.');});
}

function openBookmarkModal(item={}){
  $('#modalContent').innerHTML=`<div class="section-title"><h2>${item.id?'Edit':'Add'} Bookmark</h2><button class="btn" id="closeModal">✕</button></div><div class="form-grid"><div class="field full"><label>Title</label><input id="mTitle" class="input" value="${escapeHtml(item.title||'')}"></div><div class="field full"><label>URL</label><input id="mUrl" class="input" value="${escapeHtml(item.url||'')}"></div><div class="field"><label>Category</label><select id="mCategory" class="select">${CATEGORIES.map(c=>`<option ${c.name===(item.category||'')?'selected':''}>${escapeHtml(c.name)}</option>`).join('')}<option ${item.category==='Other'?'selected':''}>Other</option></select></div><div class="field"><label>Difficulty</label><select id="mDifficulty" class="select">${DIFFICULTIES.map(x=>`<option ${x===(item.difficulty||'beginner')?'selected':''}>${x}</option>`).join('')}</select></div><div class="field full"><label>Tags (comma separated)</label><input id="mTags" class="input" value="${escapeHtml((item.tags||[]).join(', '))}"></div><div class="field full"><label>Collections (comma separated)</label><input id="mCollections" class="input" value="${escapeHtml((item.collections||[]).join(', '))}"></div><div class="field full"><label>Description</label><textarea id="mDescription" class="textarea" rows="4">${escapeHtml(item.description||'')}</textarea></div><div class="field full"><label>Personal notes</label><textarea id="mNotes" class="textarea" rows="4">${escapeHtml(item.notes||'')}</textarea></div></div><div class="toolbar" style="margin-top:14px"><button class="btn primary" id="saveBookmark">Save Bookmark</button></div>`;
  $('#modal').classList.add('open'); $('#closeModal').onclick=()=>$('#modal').classList.remove('open');
  $('#saveBookmark').onclick=async()=>{const b={id:item.id||makeId(),title:$('#mTitle').value.trim(),url:$('#mUrl').value.trim(),category:$('#mCategory').value,tags:$('#mTags').value.split(',').map(x=>x.trim()).filter(Boolean),collections:$('#mCollections').value.split(',').map(x=>x.trim()).filter(Boolean),difficulty:$('#mDifficulty').value,type:item.type||'documentation',description:$('#mDescription').value.trim(),notes:$('#mNotes').value.trim(),createdAt:item.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(!b.title||!b.url){toast('Title and URL are required.');return}const i=bookmarks.findIndex(x=>x.id===b.id);if(i>=0)bookmarks[i]=b;else bookmarks.unshift(b);await saveBookmarks(bookmarks);$('#modal').classList.remove('open');renderBookmarks();renderStats();toast('Bookmark saved.');};
}

function renderCollections(){
  const map={}; bookmarks.forEach(b=>(b.collections||[]).forEach(c=>(map[c]??=[]).push(b))); const names=Object.keys(map);
  $('#collectionGrid').innerHTML=names.length?names.map(c=>`<div class="card"><h3>📚 ${escapeHtml(c)}</h3><div class="stat">${map[c].length}</div><div class="muted small">resources</div><button class="btn" data-collection="${escapeHtml(c)}" style="margin-top:10px">Open Collection</button></div>`).join(''):'<div class="empty">No collections yet. Add a collection name while editing a bookmark.</div>';
  $$('#collectionGrid [data-collection]').forEach(b=>b.onclick=()=>{showSection('bookmarks');$('#bookmarkSearch').value=b.dataset.collection;renderBookmarks();});
}

function renderRoadmap(){
  const done=ROADMAP.filter(([n,s])=>(learning[n]||s)==='Completed').length; const progress=pct(done,ROADMAP.length);$('#roadmapProgress').textContent=`${progress}%`;$('#roadmapList').innerHTML=ROADMAP.map(([name,defaultStatus],i)=>{const status=learning[name]||defaultStatus;return `<div class="health-row"><span><strong>${String(i+1).padStart(2,'0')}</strong> · ${escapeHtml(name)}</span><select class="select" style="width:170px" data-learn="${escapeHtml(name)}"><option ${status==='Not Started'?'selected':''}>Not Started</option><option ${status==='Learning'?'selected':''}>Learning</option><option ${status==='Completed'?'selected':''}>Completed</option></select></div>`}).join('');
  $$('#roadmapList [data-learn]').forEach(s=>s.onchange=async()=>{learning[s.dataset.learn]=s.value;await saveLearning(learning);renderRoadmap();renderLearning();renderStats();});
}

function renderLearning(){
  $('#learningList').innerHTML=ROADMAP.map(([name,status])=>{const v=learning[name]||status;return `<div class="health-row"><span>${escapeHtml(name)}</span><span class="pill">${escapeHtml(v)}</span></div>`}).join(''); const done=ROADMAP.filter(([n,s])=>(learning[n]||s)==='Completed').length; $('#learningStats').innerHTML=`<div class="stat">${pct(done,ROADMAP.length)}%</div><p class="muted">${done} of ${ROADMAP.length} roadmap stages completed.</p><div class="health-row"><span>Bookmarks</span><strong>${bookmarks.length}</strong></div><div class="health-row"><span>Notes</span><strong>${Object.keys(notes).length}</strong></div><div class="health-row"><span>Technologies</span><strong>${new Set(bookmarks.map(b=>b.category)).size}</strong></div>`;
}

function renderToolbox(){const q=($('#toolboxSearch').value||'').toLowerCase();const tools=CATEGORIES.flatMap(c=>c.tools.map(t=>({tool:t,category:c.name,icon:c.icon}))).filter(x=>x.tool.toLowerCase().includes(q)||x.category.toLowerCase().includes(q));$('#toolboxGrid').innerHTML=tools.map(x=>`<button class="tech" data-toolbox="${escapeHtml(x.tool)}">${x.icon}<br><strong>${escapeHtml(x.tool)}</strong><br><span class="small muted">${escapeHtml(x.category)}</span></button>`).join('');$$('#toolboxGrid [data-toolbox]').forEach(b=>b.onclick=()=>{showSection('search');$('#searchQuery').value=b.dataset.toolbox;runSearch();});}

function currentSearchFilters(){const cats=[...$('#searchCategory').selectedOptions].map(o=>o.value);const tags=$('#searchTags').value.split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);return {q:$('#searchQuery').value.trim().toLowerCase(),cats,tags,type:$('#searchType').value,diff:$('#searchDifficulty').value,mode:$('#filterMode').value};}

async function runSearch(){const f=currentSearchFilters();let list=resources.filter(r=>{const text=JSON.stringify(r).toLowerCase();const qOk=!f.q||text.includes(f.q);const catOk=!f.cats.length||f.cats.includes(r.category);const tagOk=!f.tags.length||f.tags.some(t=>(r.tags||[]).map(x=>x.toLowerCase()).includes(t));const typeOk=!f.type||r.type===f.type;const diffOk=!f.diff||r.difficulty===f.diff;return f.mode==='OR'&& (f.cats.length||f.tags.length||f.type||f.diff) ? (qOk&&(catOk||tagOk||typeOk||diffOk)) : (qOk&&catOk&&tagOk&&typeOk&&diffOk);});
  $('#resultCount').textContent=`${list.length} results`; $('#resultsBody').innerHTML=list.length?list.map(r=>`<tr><td><strong>${escapeHtml(r.title)}</strong><br><span class="muted small">${escapeHtml(r.description||r.url)}</span></td><td>${escapeHtml(r.category)}</td><td>${(r.tags||[]).map(t=>`<span class="pill">#${escapeHtml(t)}</span> `).join('')}</td><td>${escapeHtml(r.type)}</td><td>${escapeHtml(r.difficulty)}</td><td><div class="toolbar"><button class="btn" data-result-open="${encodeURIComponent(r.url)}">Open</button><button class="btn" data-result-bookmark="${encodeURIComponent(JSON.stringify(r))}">⭐</button></div></td></tr>`).join(''):'<tr><td colspan="6"><div class="empty">No local resources matched. Try GitHub Search or clear filters.</div></td></tr>';
  $$('#resultsBody [data-result-open]').forEach(b=>b.onclick=()=>openUrl(decodeURIComponent(b.dataset.resultOpen)));
  $$('#resultsBody [data-result-bookmark]').forEach(b=>b.onclick=async()=>{const r=JSON.parse(decodeURIComponent(b.dataset.resultBookmark));if(!bookmarks.some(x=>x.url===r.url)){bookmarks.unshift({...r,id:makeId(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),collections:[]});await saveBookmarks(bookmarks);renderBookmarks();renderStats();toast('Added to bookmarks.')}else toast('Already bookmarked.');});
}

async function githubSearch(){const q=$('#searchQuery').value.trim();if(!q){toast('Enter a GitHub search query.');return}$('#resultsBody').innerHTML='<tr><td colspan="6"><div class="empty">Searching GitHub…</div></td></tr>';try{const c=await getConfig();const headers=c.token?{Authorization:`Bearer ${c.token}`,Accept:'application/vnd.github+json'}:{Accept:'application/vnd.github+json'};const res=await fetch(`https://api.github.com/search/repositories?q=${encodeURIComponent(q)}&per_page=30&sort=stars&order=desc`,{headers,cache:'no-store'});if(!res.ok)throw new Error(`${res.status} ${res.statusText}`);const data=await res.json();const list=data.items||[];$('#resultCount').textContent=`${list.length} GitHub repositories`;$('#resultsBody').innerHTML=list.map(r=>`<tr><td><strong>${escapeHtml(r.full_name)}</strong><br><span class="muted small">${escapeHtml(r.description||'No description')}</span></td><td>GitHub</td><td>${(r.topics||[]).map(t=>`<span class="pill">#${escapeHtml(t)}</span> `).join('')}</td><td>github-repository</td><td>${r.stargazers_count>5000?'advanced':'intermediate'}</td><td><div class="toolbar"><button class="btn" data-result-open="${encodeURIComponent(r.html_url)}">Open</button><button class="btn" data-github-bookmark="${encodeURIComponent(JSON.stringify(r))}">⭐</button></div></td></tr>`).join('');$$('[data-result-open]').forEach(b=>b.onclick=()=>openUrl(decodeURIComponent(b.dataset.resultOpen)));$$('[data-github-bookmark]').forEach(b=>b.onclick=async()=>{const r=JSON.parse(decodeURIComponent(b.dataset.githubBookmark));if(bookmarks.some(x=>x.url===r.html_url)){toast('Already bookmarked.');return}bookmarks.unshift({id:makeId(),title:r.full_name,url:r.html_url,category:inferCategory(r.name,(r.topics||[]).join(' ')),tags:r.topics||[],type:'github-repository',difficulty:'intermediate',description:r.description||'',collections:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});await saveBookmarks(bookmarks);renderBookmarks();renderStats();toast('GitHub repository bookmarked.');});}catch(e){toast(`GitHub search failed: ${e.message}`)}}

async function runHealth(){
  $('#healthRows').innerHTML='<div class="empty">Running checks…</div>';const checks=[];const c=config;
  const urls=[['Repository URL',c.repositoryUrl],['Raw index.html',c.rawIndexUrl],['Raw resource DB',c.rawBaseUrl?`${c.rawBaseUrl}/data/resources.json`:'' ],['Raw bookmark DB',c.rawBaseUrl?`${c.rawBaseUrl}/${c.bookmarkPath}`:'']];
  for(const [name,url] of urls){checks.push(url?{name,...await checkEndpoint(url)}:{name,url:'',ok:false,status:0,ms:0,error:'Not configured'})}
  let repoMeta=null; if(c.repositoryUrl){try{repoMeta=await getRepoMetadata()}catch{}}
  if(repoMeta) checks.push({name:'GitHub API / repository',url:c.repositoryUrl,ok:true,status:200,ms:0});
  $('#healthRows').innerHTML=checks.map(x=>`<div class="health-row"><span>${escapeHtml(x.name)}<br><span class="muted small">${escapeHtml(x.url||x.error||'')}</span></span><span class="${x.ok?'healthy':'bad'}">${x.ok?'● Healthy':'● Failed'} ${x.status||''} ${x.ms?`· ${x.ms}ms`:''}</span></div>`).join('');$('#terminal').textContent=['$ devops-explorer health',...checks.map(x=>`[${x.ok?'OK':'FAIL'}] ${x.name}${x.ms?` (${x.ms}ms)`:''}`),``,`SYSTEM: ${checks.every(x=>x.ok)?'HEALTHY':'CHECK REQUIRED'}`].join('\n');$('#githubStatus').innerHTML=checks.every(x=>x.ok)?'<span class="dot"></span>Healthy':'<span class="dot" style="background:var(--warn)"></span>Check required';$('#homeRepo').innerHTML=c.repositoryUrl?'<span class="healthy">● Configured</span>':'<span class="warning">● Configure</span>';$('#homeRaw').innerHTML=c.rawIndexUrl?'<span class="healthy">● Configured</span>':'<span class="warning">● Configure</span>';}

async function pullBookmarks(){try{const c=await getConfig();if(!c.rawBaseUrl){throw new Error('Raw base URL is not configured.')}const raw=await fetchRawFile(c.bookmarkPath);const data=JSON.parse(raw);const remote=Array.isArray(data)?data:(data.bookmarks||[]);bookmarks=remote;await saveBookmarks(bookmarks);renderBookmarks();renderStats();renderCollections();logSync(`Pulled ${remote.length} bookmarks from ${c.bookmarkPath}.`);toast('Bookmarks pulled from GitHub.')}catch(e){logSync(`Pull failed: ${e.message}`);toast(e.message)}}
async function pushBookmarks(){try{const c=await getConfig();if(!c.token)throw new Error('Add a GitHub token in Settings before pushing.');const current=await githubGetFile(c.bookmarkPath);const payload={version:1,updatedAt:new Date().toISOString(),bookmarks};const result=await githubPutFile(c.bookmarkPath,JSON.stringify(payload,null,2),`Update DevOps Explorer bookmarks (${bookmarks.length})`,current.sha);logSync(`Pushed ${bookmarks.length} bookmarks. Commit: ${result.commit?.sha?.slice(0,8)||'done'}`);toast('Bookmarks pushed to GitHub.')}catch(e){logSync(`Push failed: ${e.message}`);toast(e.message)}}
function logSync(msg){$('#syncLog').textContent=`${new Date().toLocaleString()} — ${msg}`;$('#homeSync').textContent='Last sync updated';}

function exportBookmarks(){const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),bookmarks},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`DevOps-Bookmarks-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Bookmarks exported.');}
function importBookmarks(){ $('#importFile').click(); }
$('#importFile')?.addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());const incoming=Array.isArray(data)?data:(data.bookmarks||[]);const existing=new Map(bookmarks.map(x=>[x.url,x]));let added=0;for(const b of incoming){if(!b.url)continue;if(!existing.has(b.url)){existing.set(b.url,{...b,id:b.id||makeId(),createdAt:b.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()});added++}}bookmarks=[...existing.values()];await saveBookmarks(bookmarks);renderBookmarks();renderStats();toast(`Imported ${added} new bookmarks.`)}catch(err){toast(`Import failed: ${err.message}`)}e.target.value='';});

function applyTheme(){const root=document.documentElement;const accents={blue:['#168cff','#00d8ff'],purple:['#9b6cff','#e16cff'],green:['#19c987','#72f5ae'],orange:['#ff8b2c','#ffd166']};const [a,b]=accents[config.accent]||accents.blue;root.style.setProperty('--accent',a);root.style.setProperty('--accent2',b);const light=config.theme==='light'||(config.theme==='system'&&window.matchMedia&&window.matchMedia('(prefers-color-scheme: light)').matches);if(light){root.style.setProperty('--bg','#eef5fb');root.style.setProperty('--panel','rgba(255,255,255,.88)');root.style.setProperty('--panel2','rgba(255,255,255,.72)');root.style.setProperty('--text','#10233b');root.style.setProperty('--muted','#60758e');document.body.style.background='radial-gradient(circle at 80% 10%,rgba(0,143,255,.12),transparent 30%),#eef5fb'}else{root.style.setProperty('--bg','#07111f');root.style.setProperty('--text','#e9f3ff');root.style.setProperty('--muted','#8fa8c4');document.body.style.background='radial-gradient(circle at 80% 10%,rgba(0,143,255,.14),transparent 30%),radial-gradient(circle at 10% 90%,rgba(0,214,255,.08),transparent 28%),#07111f'}}

async function loadSettings(){config=await getConfig();for(const id of ['repositoryUrl','rawBaseUrl','rawIndexUrl','branch','bookmarkPath','categoriesPath','token','theme','accent'])if($('#'+id))$('#'+id).value=config[id]||'';$('#autoHealth').checked=!!config.autoHealth;$('#settingsDiagnostics').textContent=`Extension ${APP_VERSION}. Raw launcher mode: direct raw URL. GitHub write sync: ${config.token?'configured':'not configured'}.`;applyTheme();}
async function saveSettingsForm(){const repo=$('#repositoryUrl').value.trim(); const branch=$('#branch').value.trim()||'main'; const suppliedBase=$('#rawBaseUrl').value.trim(); const suppliedIndex=$('#rawIndexUrl').value.trim(); const next={...config,repositoryUrl:repo,branch,rawBaseUrl:suppliedBase||deriveRawBase(repo,branch),rawIndexUrl:suppliedIndex||deriveRawIndex(repo,branch),bookmarkPath:$('#bookmarkPath').value.trim()||'chrome-extension/bookmark-db/bookmarks.json',categoriesPath:$('#categoriesPath').value.trim()||'chrome-extension/bookmark-db/categories.json',token:$('#token').value.trim(),theme:$('#theme').value,accent:$('#accent').value,autoHealth:$('#autoHealth').checked};config=await saveConfig(next);applyTheme();toast('Settings saved.');await loadResources();await renderStats();}

const commands=[['🔎','Search DevOps resources',()=>showSection('search')],['⭐','Open Favorites',()=>{showSection('bookmarks');$('#bookmarkSearch').value='';}],['📚','Open Collections',()=>showSection('collections')],['🩺','Run Health Check',()=>{showSection('health');runHealth()}],['🔄','Sync Bookmarks',()=>showSection('sync')],['📥','Import Bookmarks',importBookmarks],['📤','Export Bookmarks',exportBookmarks],['🧰','Open Toolbox',()=>showSection('toolbox')],['⚙️','Settings',()=>showSection('settings')],['🚀','Open Raw Explorer',()=>openRaw()]];
function openPalette(){ $('#palette').classList.add('open');$('#paletteInput').focus();renderCommands(''); }
function closePalette(){ $('#palette').classList.remove('open'); }
function renderCommands(q){const list=commands.filter(x=>x[1].toLowerCase().includes(q.toLowerCase()));$('#commands').innerHTML=list.map((x,i)=>`<div class="command" data-command="${i}"><span>${x[0]} ${x[1]}</span><span class="muted">↵</span></div>`).join('');$$('#commands [data-command]').forEach(el=>el.onclick=()=>{closePalette();list[Number(el.dataset.command)][2]()});}
function showSection(id){$$('.section').forEach(s=>s.classList.toggle('active',s.id===id));$$('.nav button[data-section]').forEach(b=>b.classList.toggle('active',b.dataset.section===id));const title=document.querySelector(`.nav button[data-section="${id}"]`)?.textContent?.replace(/^\S+\s*/,'')||'My DevOps Workspace';$('#pageTitle').textContent=title; if(id==='bookmarks')renderBookmarks();if(id==='collections')renderCollections();if(id==='roadmap')renderRoadmap();if(id==='learning')renderLearning();if(id==='toolbox')renderToolbox();if(id==='health')runHealth();if(id==='settings')loadSettings();}

function bind(){
  $$('.nav button[data-section]').forEach(b=>b.onclick=()=>showSection(b.dataset.section));$$('[data-section-jump]').forEach(b=>b.onclick=()=>showSection(b.dataset.sectionJump));
  $('#globalSearchBtn').onclick=()=>{showSection('search');$('#searchQuery').value=$('#globalSearch').value;runSearch()};$('#globalSearch').onkeydown=e=>{if(e.key==='Enter')$('#globalSearchBtn').click()};$('#runSearch').onclick=runSearch;$('#githubSearchBtn').onclick=githubSearch;$('#clearSearch').onclick=()=>{['searchQuery','searchTags'].forEach(id=>$('#'+id).value='');$('#searchType').value='';$('#searchDifficulty').value='';selectedCategories.clear();$$('#categoryChips .chip').forEach(x=>x.classList.remove('selected'));$('#searchCategory').value=[];runSearch()};$('#bookmarkSearch').oninput=renderBookmarks;$('#bookmarkCategory').onchange=renderBookmarks;$('#addBookmark').onclick=()=>openBookmarkModal();$('#exportBookmarks').onclick=exportBookmarks;$('#importBookmarks').onclick=importBookmarks;$('#newCollection').onclick=()=>openBookmarkModal({collections:['New Collection']});$('#toolboxSearch').oninput=renderToolbox;$('#runFullHealth').onclick=runHealth;$('#healthHome').onclick=()=>showSection('health');$('#pullBookmarks').onclick=pullBookmarks;$('#pushBookmarks').onclick=pushBookmarks;$('#compareBookmarks').onclick=()=>toast('Compare view: local and remote counts can be reviewed after Pull.');$('#saveSettings').onclick=saveSettingsForm;$('#openRaw').onclick=openRaw;$('#openRepo').onclick=()=>{if(config.repositoryUrl)openUrl(config.repositoryUrl);else toast('Configure repository URL first.')};$('#paletteBtn').onclick=openPalette;$('#palette').onclick=e=>{if(e.target.id==='palette')closePalette()};$('#paletteInput').oninput=e=>renderCommands(e.target.value);$('#paletteInput').onkeydown=e=>{if(e.key==='Escape')closePalette();if(e.key==='Enter')document.querySelector('#commands .command')?.click()};window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openPalette()}});
}
function openRaw(){if(!config.rawIndexUrl){toast('Configure the raw index URL first.');showSection('settings');return}chrome.tabs.create({url:chrome.runtime.getURL('pages/dashboard/raw-launcher.html')})}

async function init(){config=await getConfig();bookmarks=await getBookmarks();notes=await getNotes();learning=await getLearning();fillCategories();bind();renderQuick();renderBookmarks();renderStats();renderRecent();renderRoadmap();renderLearning();renderToolbox();await loadResources();if(config.autoHealth)runHealth();const hash=location.hash;if(hash==='#palette')openPalette();if(hash==='#settings')showSection('settings');if(hash.startsWith('#search=')){showSection('search');$('#searchQuery').value=decodeURIComponent(hash.split('=')[1]||'');runSearch()}applyTheme();}
init();
